service: templateServerlessTypescript
frameworkVersion: '3'

provider:
  name: aws
  runtime: nodejs14.x
  region: us-west-1

functions:
  hello:
    handler: services/server.hello
    events:
      - httpApi:
          path: /
          method: get

# Serverless plugins
plugins:
  - serverless-plugin-typescript
  - serverless-offline
  - serverless-domain-manager

# Resources your functions use
# resources: